//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tareas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matter
    {
        public matter()
        {
            this.homework = new HashSet<homework>();
            this.usuario_materias = new HashSet<usuario_materias>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public System.DateTime date_register { get; set; }
    
        public virtual ICollection<homework> homework { get; set; }
        public virtual ICollection<usuario_materias> usuario_materias { get; set; }
    }
}
