//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tareas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.homework = new HashSet<homework>();
            this.rateHomeWork = new HashSet<rateHomeWork>();
            this.uploadHomework = new HashSet<uploadHomework>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<homework> homework { get; set; }
        public virtual ICollection<rateHomeWork> rateHomeWork { get; set; }
        public virtual ICollection<uploadHomework> uploadHomework { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
